# Site
repository: shwetaborate/shwetaborate.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Shweta Borate
title: QA Engineer
email: shwetalh1993@gmail.com
website:  https://shwetaborate.github.io/

# Dark Mode (true/false/never)
darkmode: false

# Social links

github_username: shwetaborate
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: Shweta Borate
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Shweta Borate. I'm a QA Engineer with 3+ years of hands-on experience in both manual and automated testing of enterprise applications. I’ve worked extensively with ERP systems, API testing, and building automation frameworks that actually make life easier.

  I enjoy connecting the dots between business needs and tech solutions—whether that’s crafting smart test strategies, managing bugs, or ensuring smooth cloud deployments. I'm comfortable working in Agile teams and have a solid background in system integration and optimizing processes to keep things running efficiently.

  I am most skilled in: <mark>Manual Testing</mark>, <mark>Java</mark>, <mark>Selenium</mark>, <mark>Postman</mark>, <mark>RestAssured</mark>, <mark>SQL</mark> and <mark>AWS</mark>
content:
  # title: Projects # Title for the section
# layout: list # Type of content section (list/text)
# content:
#   - layout: top-middle
#     title: 
#     link: github.com/sproogen
#     # link_text: Project Website
#     additional_links:
#       - title:  sproogen/modern-resume-theme
#         icon: fab fa-github
#         url: github.com/sproogen/modern-resume-theme
#       # - title:  Github page for project (eg. sproogen/modern-resume-theme)
#       #   icon: fab fa-github
#       #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
#     quote: >
#       This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
#     description: | # this will include new lines to allow paragraphs
#       I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Prodigy Infotech
        #link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Software Testing Intern
        caption: April 2025 - Present
        #quote: >
        # Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            - Currently enrolled in an ongoing software testing internship, developing 5 real-time projects focused on creating test plans, writing test cases, and building automation scripts using Selenium (Java), Playwright (Python), Postman, and Rest Assured. 
            - Expected completion: May 2025. Deliverables to be hosted on GitHub. 
        
      - layout: left
        title: NRC Health
        link: https://nrchealth.com/
        link_text: NRC Health
        sub_title: QA Engineer
        caption: Feb 2022 to Aug 2022
        #quote: >
        # Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            - Conducted API, functional, and regression testing for web applications and data interfaces.
            -	Designed and executed SQL queries for data validation and supported workflows through extensive data analysis.
            -	Performed API testing using Postman and Swagger to ensure seamless data integration between multiple systems.
            -	Backend Testing in AWS.
            -	Monitored and analyzed logs in Splunk to troubleshoot API issues and track data flow.
            -	Supported User Acceptance Testing (UAT) by validating interfaces and workflows against business requirements.
            -	Collaborated with the development team to address defects and ensure the successful deployment of software.
            -	Managed release workflows using Octopus Deploy to validate system functionality after production updates.
        
      - layout: left
        title: Enmark Systems
        link: https://eniteo.enmark.com/
        link_text: Enmark Systems
        sub_title: QA Engineer
        caption: Aug 2019 to Feb 2022
        #quote: >
        # Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            - Tested ERP software for the steel industry, validating core processes and system functionality.
            -	Performed data validation using SQL for integration between ERP systems and third-party applications.
            -	Participated in specification reviews and roadmap planning to align product development with business requirements.
            -	Analyzed and reproduced customer-reported issues by collaborating with Tier 1 and Tier 2 teams.
            -	Executed regression and patch testing for beta and production environments, ensuring system stability.
            -	Tracked and managed defects using TFS to ensure timely resolution.
            -	Worked closely with product owners and BA teams to understand user needs and define test strategies.
            -	Analyzed customer-reported issues and provided structured feedback on system enhancements.
            -	Conducted regression testing across multiple ERP modules and maintained detailed documentation.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Savitribai Phule Pune University
        caption: 2015 - 2017
        sub_title: ME Computer Engineering
        #quote: >
          #Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        #description: | # this will include new lines to allow paragraphs
          #During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

          #I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in quality Assurance and software engineering some of my other interests and hobbies are:
      - Reading Jane Austen Vriations
      - Gaming
     # - Knitting
     # - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

     # Look at this cool image  
      #![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
